"""Simple dynamic feasibility: single unconditional trajectory per init.

Unlike ``dynamic_feasibility_comparison.py``, this script:
  - uses no fix_mask (full horizon is generated by diffusion),
  - draws one sample per config (no candidate sweep / log_p argmax),
  - still open-loop rollouts planned actions from dataset episode starts.

Reports physical and per-dimension-normalized L2 gaps.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

import gym
import numpy as np
import torch
from omegaconf import OmegaConf

from cleandiffuser.classifier import CumRewClassifier
from cleandiffuser.dataset.d4rl_mujoco_dataset import D4RLMuJoCoDataset
from cleandiffuser.diffusion import DiscreteDiffusionSDE
from cleandiffuser.diffusion.guidance import validate_guidance_config
from cleandiffuser.nn_classifier import HalfJannerUNet1d
from cleandiffuser.nn_diffusion import JannerUNet1d
from d4rl_render_utils import make_sim_eval_env, resolve_ckpt_stem
from dynamic_feasibility_comparison import (
    _feasibility_gaps,
    _load_task_settings,
    _log,
    _mean_std,
    _obs_std_vector,
    _open_loop_rollout_obs,
    _sample_initial_conditions,
)
from guidance_comparison_eval import build_configs
from utils import set_seed

os.environ.setdefault("MUJOCO_GL", "disable")


def _load_agent_simple(
    args,
    save_path: str,
    obs_dim: int,
    act_dim: int,
    horizon: int,
) -> DiscreteDiffusionSDE:
    nn_diffusion = JannerUNet1d(
        obs_dim + act_dim,
        model_dim=args.model_dim,
        emb_dim=args.model_dim,
        dim_mult=args.dim_mult,
        timestep_emb_type="positional",
        attention=False,
        kernel_size=5,
    )
    nn_classifier = HalfJannerUNet1d(
        horizon,
        obs_dim + act_dim,
        out_dim=1,
        model_dim=args.model_dim,
        emb_dim=args.model_dim,
        dim_mult=args.dim_mult,
        timestep_emb_type="positional",
        kernel_size=3,
    )
    classifier = CumRewClassifier(nn_classifier, device=args.device)

    fix_mask = torch.zeros((horizon, obs_dim + act_dim))
    loss_weight = torch.ones((horizon, obs_dim + act_dim))

    agent = DiscreteDiffusionSDE(
        nn_diffusion,
        None,
        fix_mask=fix_mask,
        loss_weight=loss_weight,
        classifier=classifier,
        ema_rate=args.ema_rate,
        device=args.device,
        diffusion_steps=args.diffusion_steps,
        training_diffusion_steps=args.training_diffusion_steps,
        predict_noise=args.predict_noise,
    )

    ckpt_stem = resolve_ckpt_stem(str(args.ckpt))
    agent.load(save_path + f"diffusion_ckpt_{ckpt_stem}.pt")
    agent.classifier.load(save_path + f"classifier_ckpt_{ckpt_stem}.pt")
    agent.eval()
    return agent


def _sample_single_plan(
    agent: DiscreteDiffusionSDE,
    normalizer,
    prior: torch.Tensor,
    args,
    config: dict,
    obs_dim: int,
    act_dim: int,
) -> tuple[np.ndarray, np.ndarray]:
    prior.zero_()

    traj, _ = agent.sample(
        prior,
        solver=args.solver,
        n_samples=1,
        sample_steps=args.sampling_steps,
        sample_step_schedule=args.sample_step_schedule,
        use_ema=args.use_ema,
        w_cg=config["w_cg"],
        guidance_mode=config["guidance_mode"],
        optimization_guidance_scale=config["optimization_guidance_scale"],
        optimization_guidance_last_steps=args.optimization_guidance_last_steps,
        temperature=args.temperature,
    )

    plan = traj[0].detach().cpu().numpy()
    planned_obs = normalizer.unnormalize(plan[:, :obs_dim])
    planned_act = np.clip(plan[:, obs_dim:], -1.0, 1.0)
    return planned_obs.astype(np.float32), planned_act.astype(np.float32)


def _collect_paired_trajectories(
    env,
    agent: DiscreteDiffusionSDE,
    normalizer,
    obs_std: np.ndarray,
    raw_dataset: dict,
    args,
    configs: list[dict],
    obs_dim: int,
    act_dim: int,
) -> dict[str, list[dict]]:
    inits = _sample_initial_conditions(
        env,
        raw_dataset,
        count=args.min_trajectories,
        seed=args.seed,
        init_mode=args.init_mode,
    )

    prior = torch.zeros((1, args.horizon, obs_dim + act_dim), device=args.device)
    samples: dict[str, list[dict]] = {cfg["name"]: [] for cfg in configs}

    for init in inits:
        qpos = init["qpos"]
        qvel = init["qvel"]

        for config in configs:
            validate_guidance_config(
                str(config["guidance_mode"]),
                float(config["w_cg"]),
                float(config["optimization_guidance_scale"]),
            )
            planned_obs, planned_act = _sample_single_plan(
                agent,
                normalizer,
                prior,
                args,
                config,
                obs_dim,
                act_dim,
            )
            rollout_obs = _open_loop_rollout_obs(
                env, qpos, qvel, planned_act, args.horizon, obs_dim
            )
            gaps = _feasibility_gaps(
                planned_obs,
                rollout_obs,
                obs_std,
                store_per_step=args.store_per_step,
            )
            samples[config["name"]].append(
                {
                    "traj_idx": init["traj_idx"],
                    "init_mode": init["init_mode"],
                    "dataset_index": init["dataset_index"],
                    "config": config["name"],
                    **gaps,
                }
            )

        if (init["traj_idx"] + 1) % 10 == 0 or init["traj_idx"] + 1 == args.min_trajectories:
            _log(f"[progress] {init['traj_idx'] + 1}/{args.min_trajectories} initial conditions done")

    return samples


def _summarize_config(samples: list[dict], config: dict) -> dict:
    mean_future = [s["mean_l2_future"] for s in samples]
    mean_norm_future = [s["mean_l2_norm_future"] for s in samples]
    m_future, s_future = _mean_std(mean_future)
    m_norm_future, s_norm_future = _mean_std(mean_norm_future)
    return {
        "n_trajectories": len(samples),
        "mean_gap_mean_l2_future": m_future,
        "std_gap_mean_l2_future": s_future,
        "mean_gap_mean_l2_norm_future": m_norm_future,
        "std_gap_mean_l2_norm_future": s_norm_future,
        "guidance_mode": config["guidance_mode"],
        "w_cg": config["w_cg"],
        "optimization_guidance_scale": config["optimization_guidance_scale"],
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-dir", default="/u/rzhang26/CleanDiffuser")
    parser.add_argument("--task", default="hopper-medium-v2")
    parser.add_argument("--ckpt", default="latest")
    parser.add_argument("--run-suffix", default="medium_expert_v4_reroll")
    parser.add_argument(
        "--dataset-h5path",
        default="/u/rzhang26/.d4rl/datasets/hopper_medium_expert_v4_reroll.hdf5",
    )
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--min-trajectories", type=int, default=100)
    parser.add_argument("--output-dir", default=None)
    parser.add_argument(
        "--init-mode",
        choices=("dataset_episode_starts", "env_reset"),
        default="dataset_episode_starts",
    )
    parser.add_argument(
        "--configs",
        default="monte_carlo_w_cg0,standard_w_cg0p3,optimization_scale_0p1,optimization_scale_0p25",
    )
    parser.add_argument("--opt-scales", default="0.05,0.1,0.25,0.5")
    parser.add_argument("--horizon", type=int, default=None)
    parser.add_argument("--model-dim", type=int, default=32)
    parser.add_argument("--dim-mult", default=None)
    parser.add_argument("--diffusion-steps", type=int, default=20)
    parser.add_argument("--sampling-steps", type=int, default=20)
    parser.add_argument("--training-diffusion-steps", type=int, default=20)
    parser.add_argument("--sample-step-schedule", default="uniform")
    parser.add_argument("--optimization-guidance-last-steps", type=int, default=None)
    parser.add_argument("--solver", default="ddpm")
    parser.add_argument("--temperature", type=float, default=0.5)
    parser.add_argument("--use-ema", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--predict-noise", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--ema-rate", type=float, default=0.9999)
    parser.add_argument("--terminal-penalty", type=float, default=-100.0)
    parser.add_argument("--discount", type=float, default=0.997)
    parser.add_argument("--store-per-step", action="store_true")
    args = parser.parse_args()

    repo_dir = Path(args.repo_dir)
    task_settings = _load_task_settings(repo_dir, args.task)
    if args.horizon is None:
        args.horizon = int(task_settings["horizon"])
    if args.dim_mult is None:
        args.dim_mult = task_settings["dim_mult"]
    elif isinstance(args.dim_mult, str):
        args.dim_mult = [int(x) for x in args.dim_mult.split(",") if x.strip()]
    else:
        args.dim_mult = list(args.dim_mult)

    args.device = args.device if torch.cuda.is_available() else "cpu"
    if args.optimization_guidance_last_steps is None:
        args.optimization_guidance_last_steps = args.sampling_steps // 2
    set_seed(args.seed)

    config_names = [x.strip() for x in args.configs.split(",") if x.strip()]
    include_monte_carlo = "monte_carlo_w_cg0" in config_names
    opt_scales = [float(x.strip()) for x in args.opt_scales.split(",") if x.strip()]
    configs = build_configs(
        opt_scales=opt_scales,
        include_monte_carlo=include_monte_carlo,
        config_names=config_names,
    )

    save_path = f"results/diffuser_d4rl_mujoco/{args.task}/"
    if args.run_suffix:
        save_path = f"{save_path}{args.run_suffix}/"

    if args.output_dir:
        output_dir = Path(args.output_dir)
    else:
        run_tag = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_dir = Path(args.repo_dir) / save_path / "dynamic_feasibility_simple" / run_tag
    output_dir.mkdir(parents=True, exist_ok=True)

    _log("============================================================")
    _log("Simple dynamic feasibility (single sample, no fix_mask)")
    _log("============================================================")
    _log(f"task={args.task} ckpt={args.ckpt} save_path={save_path}")
    _log(f"horizon={args.horizon} dim_mult={args.dim_mult}")
    _log(
        f"diffusion_steps={args.diffusion_steps} sampling_steps={args.sampling_steps} "
        f"training_diffusion_steps={args.training_diffusion_steps} "
        f"opt_guidance_last_steps={args.optimization_guidance_last_steps}"
    )
    _log(f"configs={[c['name'] for c in configs]}")
    _log(f"min_trajectories={args.min_trajectories} init_mode={args.init_mode} seed={args.seed}")
    _log(f"output_dir={output_dir}")

    env_data = gym.make(args.task)
    raw_dataset = env_data.get_dataset(h5path=str(args.dataset_h5path))
    env_data.close()

    if args.init_mode == "dataset_episode_starts":
        for key in ("infos/qpos", "infos/qvel"):
            if key not in raw_dataset:
                raise KeyError(
                    f"{key} missing from dataset; use --init-mode env_reset instead."
                )

    dataset = D4RLMuJoCoDataset(
        raw_dataset,
        horizon=args.horizon,
        terminal_penalty=args.terminal_penalty,
        discount=args.discount,
    )
    obs_dim, act_dim = dataset.o_dim, dataset.a_dim
    normalizer = dataset.get_normalizer()
    obs_std = _obs_std_vector(normalizer, obs_dim)
    _log(
        "obs normalizer std (dataset z-score): "
        + ", ".join(f"{v:.4f}" for v in obs_std.tolist())
    )

    agent = _load_agent_simple(args, save_path, obs_dim, act_dim, args.horizon)
    env_eval, sim_name = make_sim_eval_env(args.task, sim_env_name=None, render=False)
    _log(f"rollout sim env: {sim_name}")

    all_samples = _collect_paired_trajectories(
        env_eval,
        agent,
        normalizer,
        obs_std,
        raw_dataset,
        args,
        configs,
        obs_dim,
        act_dim,
    )
    env_eval.close()

    final_summary = {"configs": {}}
    _log("\n========== Final simple dynamic feasibility summary ==========")
    for config in configs:
        name = config["name"]
        samples = all_samples[name]
        final_summary["configs"][name] = _summarize_config(samples, config)
        row = final_summary["configs"][name]
        _log(
            f"{name:28s} n={row['n_trajectories']:4d}  "
            f"mean_l2_future={row['mean_gap_mean_l2_future']:7.4f} ± "
            f"{row['std_gap_mean_l2_future']:6.4f}  "
            f"mean_l2_norm_future={row['mean_gap_mean_l2_norm_future']:7.4f} ± "
            f"{row['std_gap_mean_l2_norm_future']:6.4f}"
        )

    payload = {
        "eval_type": "simple_single_sample_no_mask",
        "task": args.task,
        "ckpt": args.ckpt,
        "run_suffix": args.run_suffix,
        "dataset_h5path": args.dataset_h5path,
        "sim_env": sim_name,
        "horizon": args.horizon,
        "min_trajectories": args.min_trajectories,
        "init_mode": args.init_mode,
        "seed": args.seed,
        "solver": args.solver,
        "diffusion_steps": args.diffusion_steps,
        "sampling_steps": args.sampling_steps,
        "training_diffusion_steps": args.training_diffusion_steps,
        "optimization_guidance_last_steps": args.optimization_guidance_last_steps,
        "sample_step_schedule": args.sample_step_schedule,
        "configs": configs,
        "obs_normalizer_std": obs_std.astype(float).tolist(),
        "samples": all_samples,
        "final_summary": final_summary,
        "output_dir": str(output_dir),
        "method": (
            "Single unconditional diffusion sample per init (no fix_mask, no candidate "
            "sweep). Open-loop rollout from dataset episode-start MuJoCo states."
        ),
    }

    summary_path = output_dir / "summary.json"
    with open(summary_path, "w") as f:
        json.dump(payload, f, indent=2)
    _log(f"Saved {summary_path}")

    if any(len(all_samples[c["name"]]) < args.min_trajectories for c in configs):
        missing = [c["name"] for c in configs if len(all_samples[c["name"]]) < args.min_trajectories]
        _log(f"[warn] Configs below min_trajectories: {missing}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
